version: '3.8'
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db_data
    expose:
      - "27017"
    ports:
      - "27017:27017"
  bot:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    volumes:
      - ./bot:/bot

volumes:
  mongo_data:
