version: '3.8'
services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    expose:
      - "27017"
    restart: always

  bot:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    volumes:
      - ./bot:/bot
    restart: always

volumes:
  mongo_data:
